on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - 'main'
    tags:
      - 'v*'

jobs:

  detectToolVersions:
    name: "Detect Tool Versions"

    runs-on: ubuntu-latest

    outputs:
      elixir: "${{ steps.versions.outputs.elixir }}"
      erlang: "${{ steps.versions.outputs.erlang }}"

    steps:
      - uses: actions/checkout@v6.0.1
      - name: Detect Versions
        id: versions
        uses: actions/github-script@v8
        with:
          script: |
            const fs = require('node:fs');
            const versions = fs.readFileSync('.tool-versions', 'utf8');

            const regex = /^(# )?(?<toolName>([\w_-]+)) +(?<version>[^\s#]+)(?: +[^\s#]+)* *(?: #(?<comment>.*))?$/gm;

            [...versions.matchAll(regex)]
              .map(match => match.groups)
              .forEach(({toolName, version}) => {
                core.setOutput(toolName, version);
                console.log(`${toolName}: ${version}`);
              });

  format:
    name: Check Formatting
    
    runs-on: ubuntu-latest

    env:
      MIX_ENV: dev

    steps:
      - uses: actions/checkout@v6.0.1
      - uses: erlef/setup-beam@v1
        id: setupBEAM
        with:
          version-file: ".tool-versions"
          version-type: strict
      - uses: actions/cache@v5
        with:
          path: |-
            deps
            _build
          key: "${{ format('{0}-{1}-{2}-{3}-{4}', env.MIX_ENV, runner.os, steps.setupBEAM.outputs.otp-version, steps.setupBEAM.outputs.elixir-version, hashFiles('mix.exs')) }}"
          restore-keys: "${{ format('{0}-{1}-{2}-{3}-', env.MIX_ENV, runner.os, steps.setupBEAM.outputs.otp-version, steps.setupBEAM.outputs.elixir-version) }}"
      - run: mix deps.get
      - run: mix deps.compile
      - run: mix format --check-formatted

  test:
    name: Run Tests & Submit Coverage (${{ matrix.name }})

    runs-on: "${{ matrix.os }}"

    needs: ["detectToolVersions"]

    env:
      MIX_ENV: test

    strategy:
      fail-fast: false
      matrix:
        include:
          # Lowest Supported
          - os: ubuntu-22.04
            elixir: "1.12.3"
            erlang: "24.2"
            name: "lowest"
            unstable: false
          # Latest Supported
          - os: ubuntu-latest
            elixir: "${{ needs.detectToolVersions.outputs.elixir }}"
            erlang: "${{ needs.detectToolVersions.outputs.erlang }}"
            name: "latest"
            unstable: false
          # Test Main
          - os: ubuntu-latest
            elixir: "main"
            erlang: "${{ needs.detectToolVersions.outputs.erlang }}"
            name: "main"
            unstable: true

    steps:
      - uses: actions/checkout@v6.0.1
      - uses: erlef/setup-beam@v1
        id: setupBEAM
        with:
          otp-version: "${{ matrix.erlang }}"
          elixir-version: "${{ matrix.elixir }}"
          version-type: strict
      - uses: actions/cache@v5
        with:
          path: |-
            deps
            _build
          key: "${{ format('{0}-{1}-{2}-{3}-{4}', env.MIX_ENV, runner.os, steps.setupBEAM.outputs.otp-version, steps.setupBEAM.outputs.elixir-version, hashFiles('mix.exs')) }}"
          restore-keys: "${{ format('{0}-{1}-{2}-{3}-', env.MIX_ENV, runner.os, steps.setupBEAM.outputs.otp-version, steps.setupBEAM.outputs.elixir-version) }}"
      - run: mix deps.get
      - run: mix deps.compile
      - run: mix compile --warning-as-errors
        continue-on-error: ${{ matrix.unstable }}
      - run: mix coveralls.github || mix test
        continue-on-error: ${{ matrix.unstable }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  credo:
    name: Check Credo

    runs-on: ubuntu-latest

    env:
      MIX_ENV: dev

    steps:
      - uses: actions/checkout@v6.0.1
      - uses: erlef/setup-elixir@v1
        id: setupBEAM
        with:
          version-file: ".tool-versions"
          version-type: strict
      - uses: actions/cache@v5
        with:
          path: |-
            deps
            _build
          key: "${{ format('{0}-{1}-{2}-{3}-{4}', env.MIX_ENV, runner.os, steps.setupBEAM.outputs.otp-version, steps.setupBEAM.outputs.elixir-version, hashFiles('mix.exs')) }}"
          restore-keys: "${{ format('{0}-{1}-{2}-{3}-', env.MIX_ENV, runner.os, steps.setupBEAM.outputs.otp-version, steps.setupBEAM.outputs.elixir-version) }}"
      - run: mix deps.get
      - run: mix deps.compile
      - run: mix compile --warning-as-errors
      - run: mix credo --strict

  dialyzer:
    name: "Check Dialyzer"

    runs-on: ubuntu-latest

    env:
      MIX_ENV: dev

    steps:
      - uses: actions/checkout@v6.0.1
      - uses: erlef/setup-elixir@v1
        id: setupBEAM
        with:
          version-file: ".tool-versions"
          version-type: strict
      - uses: actions/cache@v5
        with:
          path: |-
            deps
            _build
          key: "${{ format('{0}-{1}-{2}-{3}-{4}', env.MIX_ENV, runner.os, steps.setupBEAM.outputs.otp-version, steps.setupBEAM.outputs.elixir-version, hashFiles('mix.exs')) }}"
          restore-keys: "${{ format('{0}-{1}-{2}-{3}-', env.MIX_ENV, runner.os, steps.setupBEAM.outputs.otp-version, steps.setupBEAM.outputs.elixir-version) }}"
      - run: mix deps.get
      - run: mix deps.compile
      - run: mix compile --warning-as-errors
      - run: mix dialyzer

  docs:
    name: "Generate Docs"

    runs-on: ubuntu-latest

    env:
      MIX_ENV: dev

    steps:
      - uses: actions/checkout@v6.0.1
      - uses: erlef/setup-elixir@v1
        id: setupBEAM
        with:
          version-file: ".tool-versions"
          version-type: strict
      - uses: actions/cache@v5
        with:
          path: |-
            deps
            _build
          key: "${{ format('{0}-{1}-{2}-{3}-{4}', env.MIX_ENV, runner.os, steps.setupBEAM.outputs.otp-version, steps.setupBEAM.outputs.elixir-version, hashFiles('mix.exs')) }}"
          restore-keys: "${{ format('{0}-{1}-{2}-{3}-', env.MIX_ENV, runner.os, steps.setupBEAM.outputs.otp-version, steps.setupBEAM.outputs.elixir-version) }}"
      - run: mix deps.get
      - run: mix deps.compile
      - run: mix compile --warning-as-errors
      - run: mix docs
      - uses: actions/upload-artifact@v6
        with:
          name: docs
          path: doc

  sobelow:
    runs-on: ubuntu-latest
    name: Sobelow Job

    steps:
      - uses: actions/checkout@v6.0.1
      - id: run-action
        uses: sobelow/action@4c2cc216597acef2c5f8b4b2e49ad591be36ce36 # v1.2.0
        with:
          flags: '--skip'
      - uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: results.sarif