on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - 'main'
    tags:
      - 'v*'

jobs:

  detectToolVersions:
    name: "Detect Tool Versions"

    runs-on: ubuntu-latest

    outputs:
      elixir: "${{ steps.versions.outputs.elixir }}"
      erlang: "${{ steps.versions.outputs.erlang }}"

    steps:
      - uses: actions/checkout@v4
      - name: Detect Versions
        id: versions
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('node:fs');
            const versions = fs.readFileSync('.tool-versions', 'utf8');

            const regex = /^(# )?(?<toolName>([\w_-]+)) +(?<version>[^\s#]+)(?: +[^\s#]+)* *(?: #(?<comment>.*))?$/gm;

            [...versions.matchAll(regex)]
              .map(match => match.groups)
              .forEach(({toolName, version}) => {
                core.setOutput(toolName, version);
                console.log(`${toolName}: ${version}`);
              });

  format:
    name: Check Formatting
    
    runs-on: ubuntu-latest

    env:
      MIX_ENV: dev

    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        id: setupBEAM
        with:
          version-file: ".tool-versions"
          version-type: strict
      - uses: actions/cache@v4
        with:
          path: deps
          key: deps-${{ runner.os }}-${{ steps.setupBEAM.outputs.otp-version }}-${{ steps.setupBEAM.outputs.elixir-version }}-${{ hashFiles('mix.exs') }}
          restore-keys: |
            deps-${{ runner.os }}-${{ steps.setupBEAM.outputs.otp-version }}-${{ steps.setupBEAM.outputs.elixir-version }}-
      - run: mix deps.get
      - uses: actions/cache@v4
        with:
          path: _build/dev
          key: compile-${{ env.MIX_ENV }}-${{ runner.os }}-${{ steps.setupBEAM.outputs.otp-version }}-${{ steps.setupBEAM.outputs.elixir-version }}-${{ hashFiles('mix.exs') }}
          restore-keys: |
            compile-${{ env.MIX_ENV }}-${{ runner.os }}-${{ steps.setupBEAM.outputs.otp-version }}-${{ steps.setupBEAM.outputs.elixir-version }}-
      - run: mix deps.compile
      - run: mix format --check-formatted


  test:
    name: Run Tests & Submit Coverage

    runs-on: "${{ matrix.os }}"

    needs: ["detectToolVersions"]

    env:
      MIX_ENV: test

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-20.04
            elixir: "1.11.4"
            erlang: "22.3"
          - os: ubuntu-latest
            elixir: "${{ needs.detectToolVersions.outputs.elixir }}"
            erlang: "${{ needs.detectToolVersions.outputs.erlang }}"
          - os: ubuntu-latest
            elixir: "main"
            erlang: "master"

    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        id: setupBEAM
        with:         
          otp-version: "${{ matrix.erlang }}"
          elixir-version: "${{ matrix.elixir }}"
          version-type: strict
      - uses: actions/cache@v4
        with:
          path: deps
          key: deps-${{ runner.os }}-${{ steps.setupBEAM.outputs.otp-version }}-${{ steps.setupBEAM.outputs.elixir-version }}-${{ hashFiles('mix.exs') }}
          restore-keys: |
            deps-${{ runner.os }}-${{ steps.setupBEAM.outputs.otp-version }}-${{ steps.setupBEAM.outputs.elixir-version }}-
      - run: mix deps.get
      - uses: actions/cache@v4
        with:
          path: _build/test
          key: compile-${{ env.MIX_ENV }}-${{ runner.os }}-${{ steps.setupBEAM.outputs.otp-version }}-${{ steps.setupBEAM.outputs.elixir-version }}-${{ hashFiles('mix.exs') }}
          restore-keys: |
            compile-${{ env.MIX_ENV }}-${{ runner.os }}-${{ steps.setupBEAM.outputs.otp-version }}-${{ steps.setupBEAM.outputs.elixir-version }}-
      - run: mix deps.compile
      - run: mix compile --warning-as-errors
      - run: mix coveralls.github || mix test

  credo:
    name: Check Credo

    runs-on: ubuntu-latest

    env:
      MIX_ENV: dev

    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-elixir@v1
        id: setupBEAM
        with:
          version-file: ".tool-versions"
          version-type: strict
      - uses: actions/cache@v4
        with:
          path: deps
          key: deps-${{ runner.os }}-${{ steps.setupBEAM.outputs.otp-version }}-${{ steps.setupBEAM.outputs.elixir-version }}-${{ hashFiles('mix.exs') }}
          restore-keys: |
            deps-${{ runner.os }}-${{ steps.setupBEAM.outputs.otp-version }}-${{ steps.setupBEAM.outputs.elixir-version }}-
      - run: mix deps.get
      - uses: actions/cache@v4
        with:
          path: _build/dev
          key: compile-${{ env.MIX_ENV }}-${{ runner.os }}-${{ steps.setupBEAM.outputs.otp-version }}-${{ steps.setupBEAM.outputs.elixir-version }}-${{ hashFiles('mix.exs') }}
          restore-keys: |
            compile-${{ env.MIX_ENV }}-${{ runner.os }}-${{ steps.setupBEAM.outputs.otp-version }}-${{ steps.setupBEAM.outputs.elixir-version }}-
      - run: mix deps.compile
      - run: mix compile --warning-as-errors
      - run: mix credo --strict

  dialyzer_plt:
    name: Generate Dialyzer PLT

    runs-on: ubuntu-latest

    env:
      MIX_ENV: dev
      DIALYZER_PLT_PRIV: true

    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-elixir@v1
        id: setupBEAM
        with:
          version-file: ".tool-versions"
          version-type: strict
      - uses: actions/cache@v4
        with:
          path: deps
          key: deps-${{ runner.os }}-${{ steps.setupBEAM.outputs.otp-version }}-${{ steps.setupBEAM.outputs.elixir-version }}-${{ hashFiles('mix.exs') }}
          restore-keys: |
            deps-${{ runner.os }}-${{ steps.setupBEAM.outputs.otp-version }}-${{ steps.setupBEAM.outputs.elixir-version }}-
      - run: mix deps.get
      - uses: actions/cache@v4
        with:
          path: _build/dev
          key: compile-${{ env.MIX_ENV }}-${{ runner.os }}-${{ steps.setupBEAM.outputs.otp-version }}-${{ steps.setupBEAM.outputs.elixir-version }}-${{ hashFiles('mix.exs') }}
          restore-keys: |
            compile-${{ env.MIX_ENV }}-${{ runner.os }}-${{ steps.setupBEAM.outputs.otp-version }}-${{ steps.setupBEAM.outputs.elixir-version }}-
      - run: mix deps.compile
      - run: mix compile --warning-as-errors
      - uses: actions/cache@v4
        with:
          path: priv/plts/
          key: dialyzer_plt_dev-${{ runner.os }}-${{ steps.setupBEAM.outputs.otp-version }}-${{ steps.setupBEAM.outputs.elixir-version }}-${{ hashFiles('mix.exs') }}
          restore-keys: |
            dialyzer_plt_dev-${{ runner.os }}-${{ steps.setupBEAM.outputs.otp-version }}-${{ steps.setupBEAM.outputs.elixir-version }}-
      - run: mix dialyzer --plt
      - uses: actions/upload-artifact@v4
        with:
          name: dialyzer_plt_dev
          path: priv/plts/

  dialyzer_test:
    name: "Check Dialyzer"

    runs-on: ubuntu-latest

    needs: ['dialyzer_plt']

    env:
      MIX_ENV: dev
      DIALYZER_PLT_PRIV: true

    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-elixir@v1
        id: setupBEAM
        with:
          version-file: ".tool-versions"
          version-type: strict
      - uses: actions/cache@v4
        with:
          path: deps
          key: deps-${{ runner.os }}-${{ steps.setupBEAM.outputs.otp-version }}-${{ steps.setupBEAM.outputs.elixir-version }}-${{ hashFiles('mix.exs') }}
          restore-keys: |
            deps-${{ runner.os }}-${{ steps.setupBEAM.outputs.otp-version }}-${{ steps.setupBEAM.outputs.elixir-version }}-
      - run: mix deps.get
      - uses: actions/cache@v4
        with:
          path: _build/dev
          key: compile-${{ env.MIX_ENV }}-${{ runner.os }}-${{ steps.setupBEAM.outputs.otp-version }}-${{ steps.setupBEAM.outputs.elixir-version }}-${{ hashFiles('mix.exs') }}
          restore-keys: |
            compile-${{ env.MIX_ENV }}-${{ runner.os }}-${{ steps.setupBEAM.outputs.otp-version }}-${{ steps.setupBEAM.outputs.elixir-version }}-
      - run: mix deps.compile
      - run: mix compile --warning-as-errors
      - uses: actions/download-artifact@v4
        with:
          name: dialyzer_plt_dev
          path: priv/plts/
      - run: mix dialyzer

  docs:
    name: "Generate Docs"

    runs-on: ubuntu-latest

    env:
      MIX_ENV: dev

    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-elixir@v1
        id: setupBEAM
        with:
          version-file: ".tool-versions"
          version-type: strict
      - uses: actions/cache@v4
        with:
          path: deps
          key: deps-${{ runner.os }}-${{ steps.setupBEAM.outputs.otp-version }}-${{ steps.setupBEAM.outputs.elixir-version }}-${{ hashFiles('mix.exs') }}
          restore-keys: |
            deps-${{ runner.os }}-${{ steps.setupBEAM.outputs.otp-version }}-${{ steps.setupBEAM.outputs.elixir-version }}-
      - run: mix deps.get
      - uses: actions/cache@v4
        with:
          path: _build/dev
          key: compile-${{ env.MIX_ENV }}-${{ runner.os }}-${{ steps.setupBEAM.outputs.otp-version }}-${{ steps.setupBEAM.outputs.elixir-version }}-${{ hashFiles('mix.exs') }}
          restore-keys: |
            compile-${{ env.MIX_ENV }}-${{ runner.os }}-${{ steps.setupBEAM.outputs.otp-version }}-${{ steps.setupBEAM.outputs.elixir-version }}-
      - run: mix deps.compile
      - run: mix compile --warning-as-errors
      - run: mix docs
      - uses: actions/upload-artifact@v4
        with:
          name: docs
          path: doc

  sobelow:
    runs-on: ubuntu-latest
    name: Sobelow Job

    steps:
      - uses: actions/checkout@v4
      - id: run-action
        uses: sobelow/action@v1
        with:
          flags: '--skip'
      - uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: results.sarif