on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - 'main'
    tags:
      - 'v*'

jobs:

  detectToolVersions:
    name: "Detect Tool Versions"

    runs-on: ubuntu-latest

    outputs:
      elixir: "${{ steps.versions.outputs.elixir }}"
      erlang: "${{ steps.versions.outputs.erlang }}"

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Detect Versions
        id: versions
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        with:
          script: |
            const fs = require('node:fs');
            const versions = fs.readFileSync('.tool-versions', 'utf8');

            const regex = /^(# )?(?<toolName>([\w_-]+)) +(?<version>[^\s#]+)(?: +[^\s#]+)* *(?: #(?<comment>.*))?$/gm;

            [...versions.matchAll(regex)]
              .map(match => match.groups)
              .forEach(({toolName, version}) => {
                core.setOutput(toolName, version);
                console.log(`${toolName}: ${version}`);
              });

  format:
    name: Check Formatting
    
    runs-on: ubuntu-latest

    env:
      MIX_ENV: dev

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: erlef/setup-beam@54075bcc5e249e4758d363f27d099f55d843f124 # v1.24.1
        id: setupBEAM
        with:
          version-file: ".tool-versions"
          version-type: strict
      - uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: |-
            deps
            _build
          key: "${{ format('{0}-{1}-{2}-{3}-{4}', env.MIX_ENV, runner.os, steps.setupBEAM.outputs.otp-version, steps.setupBEAM.outputs.elixir-version, hashFiles('mix.exs')) }}"
          restore-keys: "${{ format('{0}-{1}-{2}-{3}-', env.MIX_ENV, runner.os, steps.setupBEAM.outputs.otp-version, steps.setupBEAM.outputs.elixir-version) }}"
      - run: mix deps.get
      - run: mix deps.compile
      - run: mix format --check-formatted

  test:
    name: Run Tests & Submit Coverage (${{ matrix.name }})

    runs-on: "${{ matrix.os }}"

    needs: ["detectToolVersions"]

    env:
      MIX_ENV: test

    strategy:
      fail-fast: false
      matrix:
        include:
          # Lowest Supported
          - os: ubuntu-22.04
            elixir: "1.12.3"
            erlang: "24.2"
            name: "lowest"
            unstable: false
          # Latest Supported
          - os: ubuntu-latest
            elixir: "${{ needs.detectToolVersions.outputs.elixir }}"
            erlang: "${{ needs.detectToolVersions.outputs.erlang }}"
            name: "latest"
            unstable: false
          # Test Main
          - os: ubuntu-latest
            elixir: "main"
            erlang: "${{ needs.detectToolVersions.outputs.erlang }}"
            name: "main"
            unstable: true

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: erlef/setup-beam@54075bcc5e249e4758d363f27d099f55d843f124 # v1.24.1
        id: setupBEAM
        with:
          otp-version: "${{ matrix.erlang }}"
          elixir-version: "${{ matrix.elixir }}"
          version-type: strict
      - uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: |-
            deps
            _build
          key: "${{ format('{0}-{1}-{2}-{3}-{4}', env.MIX_ENV, runner.os, steps.setupBEAM.outputs.otp-version, steps.setupBEAM.outputs.elixir-version, hashFiles('mix.exs')) }}"
          restore-keys: "${{ format('{0}-{1}-{2}-{3}-', env.MIX_ENV, runner.os, steps.setupBEAM.outputs.otp-version, steps.setupBEAM.outputs.elixir-version) }}"
      - run: mix deps.get
      - run: mix deps.compile
      - run: mix compile --warning-as-errors
        continue-on-error: ${{ matrix.unstable }}
      - run: mix coveralls.github || mix test
        continue-on-error: ${{ matrix.unstable }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  credo:
    name: Check Credo

    runs-on: ubuntu-latest

    env:
      MIX_ENV: dev

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: erlef/setup-beam@54075bcc5e249e4758d363f27d099f55d843f124 # v1.24.1
        id: setupBEAM
        with:
          version-file: ".tool-versions"
          version-type: strict
      - uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: |-
            deps
            _build
          key: "${{ format('{0}-{1}-{2}-{3}-{4}', env.MIX_ENV, runner.os, steps.setupBEAM.outputs.otp-version, steps.setupBEAM.outputs.elixir-version, hashFiles('mix.exs')) }}"
          restore-keys: "${{ format('{0}-{1}-{2}-{3}-', env.MIX_ENV, runner.os, steps.setupBEAM.outputs.otp-version, steps.setupBEAM.outputs.elixir-version) }}"
      - run: mix deps.get
      - run: mix deps.compile
      - run: mix compile --warning-as-errors
      - run: mix credo --strict

  dialyzer:
    name: "Check Dialyzer"

    runs-on: ubuntu-latest

    env:
      MIX_ENV: dev

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: erlef/setup-beam@54075bcc5e249e4758d363f27d099f55d843f124 # v1.24.1
        id: setupBEAM
        with:
          version-file: ".tool-versions"
          version-type: strict
      - uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: |-
            deps
            _build
          key: "${{ format('{0}-{1}-{2}-{3}-{4}', env.MIX_ENV, runner.os, steps.setupBEAM.outputs.otp-version, steps.setupBEAM.outputs.elixir-version, hashFiles('mix.exs')) }}"
          restore-keys: "${{ format('{0}-{1}-{2}-{3}-', env.MIX_ENV, runner.os, steps.setupBEAM.outputs.otp-version, steps.setupBEAM.outputs.elixir-version) }}"
      - run: mix deps.get
      - run: mix deps.compile
      - run: mix compile --warning-as-errors
      - run: mix dialyzer

  docs:
    name: "Generate Docs"

    runs-on: ubuntu-latest

    env:
      MIX_ENV: dev

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: erlef/setup-beam@54075bcc5e249e4758d363f27d099f55d843f124 # v1.24.1
        id: setupBEAM
        with:
          version-file: ".tool-versions"
          version-type: strict
      - uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: |-
            deps
            _build
          key: "${{ format('{0}-{1}-{2}-{3}-{4}', env.MIX_ENV, runner.os, steps.setupBEAM.outputs.otp-version, steps.setupBEAM.outputs.elixir-version, hashFiles('mix.exs')) }}"
          restore-keys: "${{ format('{0}-{1}-{2}-{3}-', env.MIX_ENV, runner.os, steps.setupBEAM.outputs.otp-version, steps.setupBEAM.outputs.elixir-version) }}"
      - run: mix deps.get
      - run: mix deps.compile
      - run: mix compile --warning-as-errors
      - run: mix docs
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: docs
          path: doc

  sobelow:
    runs-on: ubuntu-latest
    name: Sobelow Job

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - id: run-action
        uses: sobelow/action@4c2cc216597acef2c5f8b4b2e49ad591be36ce36 # v1.2.0
        with:
          flags: '--skip'
      - uses: github/codeql-action/upload-sarif@8aad20d150bbac5944a9f9d289da16a4b0d87c1e # v4.36.2
        with:
          sarif_file: results.sarif