on:
  push:
    branches:
      - "main"

name: "Mix Dependency Submission"

permissions:
  contents: read

jobs:
  submit:
    name: "Submit"

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@df199fb7be9f65074067a9eb93f12bb4c5547cf2 # v2.13.3
        with:
          egress-policy: audit

      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v4.2.2

      - uses: erlef/mix-dependency-submission@e3e07c533ea58301b54024fbf9663e1a167840a3 # v1.2.2
